name: test

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
jobs:
  lint_shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@master

  test_action:
    runs-on: ubuntu-latest
    env:
      APP_DIR: ./example
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.6
          channel: stable

      - name: Run dart format on changed files
        uses: ProjectAJ14/flutter_diff_action@v1.0.1
        with:
          command: 'dart format --set-exit-if-changed'
          branch: ${{ github.base_ref }}

      - name: Run dart analyze on changed files
        uses: ProjectAJ14/flutter_diff_action@v1.0.1
        with:
          command: 'dart analyze --fatal-infos'
          branch: ${{ github.base_ref }}

      - name: Run test on changed files
        uses: ProjectAJ14/flutter_diff_action@v1.0.1
        with:
          command: 'flutter test'
          branch: ${{ github.base_ref }}
